### ISSUE TITLE
Can you print layouts into separate files? Or rename PDF pages to follow layout names?

### ISSUE THREAD

**Issue by danielkrajnik** [dalefugier/RealDrawings#3]
It would be helpful if you could export layouts into separate files named the same as the layout names in rhino.

For me "Rhino PDF" option exports all layouts into a single PDF with pages named 1,2,3...

**Comment by dalefugier** [comment]
Hey @danielkrajnik - printing doesn't have anything to do with this project. Please direct your question to Discourse.

https://discourse.mcneel.com/

Thanks,

-- Dale
